# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'YYPrivatePod' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for YYPrivatePod

  target 'YYPrivatePodTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YYPrivatePodUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
